language: python

matrix:
  include:
    - python: 3.6
      os: linux
    - python: 3.7
      os: linux
    - python: 3.7-dev
      os: linux
    - python: 3.6-dev
      os: osx
    - python: 3.7-dev
      os: osx
    - python: 3.6
      os: windows
    - python: 3.7
      os: windows

notifications:
  email: false

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
